apiVersion: v1
kind: Service
metadata:
  name: gestionstationski-service
spec:
  selector:
    app: gestionstationski
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8089
  type: LoadBalancer
